### ISSUE TITLE
Default GTK 3 theme folder

### ISSUE THREAD

**Issue by jimmy-lt** [logico-dev/typewriter-gtk#1]
There is no default folder for a GTK 3 theme. All GTK 3 folders are targeting a specific version. Would be great to have a `gtk-3.0` folder that can be applied whatever version is in use.

**Comment by tliron** [comment]
I second this. As it stands, it won't work in the GNOME desktop. It requires a `gtk-3.0` folder.

**Comment by tliron** [comment]
Actually, just renaming the `gtk-3.20` to `gtk-3.0` makes it appear for GNOME, but it does not render properly.

**Comment by janoamaral** [comment]
Please rename the `gtk-3.14` to `gtk-3.0`, it should work. Please confirm. Thanks.

**Comment by tliron** [comment]
That works, thanks.

**Comment by tliron** [comment]
Just so you know, with this fix I now added support for Typewriter to [install-gnome-themes](https://github.com/tliron/install-gnome-themes).
